version: '3.8'
services:
  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb
    networks:
      - sam-local
    ports:
      - "8000:8000"
    volumes:
      - "./local-dynamodb:/home/dynamodb/data"
    working_dir: /home/dynamodb
networks:
  sam-local:
